### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by reysillo** [kolonist/node-xwhois#1]
I´m adding next code in my node js app and gets error:
`const whois = require('node-xwhois');`

```javascript
Debugger listening on port 54727
/app/node_modules/node-xwhois/lib/whois.js:214
const whois = (host, options = {}) => {
                             ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

**Comment by kolonist** [comment]
Please, tell your node version.

23 нояб. 2016 г. 3:14 AM пользователь "reysillo" <notifications@github.com>
написал:

**Comment by reysillo** [comment]
You are right, I just updated from v4.4.5 to v6.9.1 and now all works well, thank you!
